version: "3"

services:
  # Agents
  university-agent:
    command: ["university --port 8020"]
    build:
      context: https://github.com/petridishdev/aries-cloudagent-python.git#openapi-demo
      dockerfile: ./docker/Dockerfile.demo
    ports:
      - 8020-8027:8020-8027
    networks:
      - aca
    environment:
      - RUNMODE=${RUNMODE}
      - DOCKERHOST=${DOCKERHOST}
      - LEDGER_URL=${LEDGER_URL}
      - GENESIS_URL=${GENESIS_URL}
    tty: true
  graduate-agent:
    command: ["graduate --port 8030"]
    build:
      context: https://github.com/petridishdev/aries-cloudagent-python.git#openapi-demo
      dockerfile: ./docker/Dockerfile.demo
    ports:
      - 8030-8037:8030-8037
    networks:
      - aca
    environment:
      - RUNMODE=${RUNMODE}
      - DOCKERHOST=${DOCKERHOST}
      - LEDGER_URL=${LEDGER_URL}
      - GENESIS_URL=${GENESIS_URL}
    tty: true
  company-agent:
    command: ["company --port 8040"]
    build:
      context: https://github.com/petridishdev/aries-cloudagent-python.git#openapi-demo
      dockerfile: ./docker/Dockerfile.demo
    ports:
      - 8040-8047:8040-8047
    networks:
      - aca
    environment:
      - RUNMODE=${RUNMODE}
      - DOCKERHOST=${DOCKERHOST}
      - LEDGER_URL=${LEDGER_URL}
      - GENESIS_URL=${GENESIS_URL}
    tty: true

  # Controllers
  university-controller:
    build:
      context: ../University/
      args:
        - RUNMODE=${RUNMODE}
        - UNIVERSITY_AGENT_HOST=${UNIVERSITY_AGENT_HOST}
    ports:
      - 9021:80
    networks:
      - aca
    depends_on:
      - university-agent

  graduate-controller:
    build:
      context: ../Graduate/
      args:
        - RUNMODE=${RUNMODE}
        - GRADUATE_AGENT_HOST=${GRADUATE_AGENT_HOST}
    ports:
      - 9031:80
    networks:
      - aca
    depends_on:
      - graduate-agent

  company-controller:
    build:
      context: ../Company/
      args:
        - RUNMODE=${RUNMODE}
        - COMPANY_AGENT_HOST=${COMPANY_AGENT_HOST}
    ports:
      - 9041:3000
    networks:
      - aca
    depends_on:
      - company-agent

networks:
  aca:
