version: "3"

services:
  # Agents
  university-agent:
    command: ["faber --port 8020"]
    build:
      context: https://github.com/mostafatalaat770/aries-cloudagent-python.git#openapi-demo
      dockerfile: ./docker/Dockerfile.demo
    ports:
      - 8020-8027:8020-8027
    networks:
      - aca
    environment:
      - RUNMODE=${RUNMODE}
      - DOCKERHOST=${DOCKERHOST}
      - LEDGER_URL=${LEDGER_URL}
      - GENESIS_URL=${GENESIS_URL}
    tty: true
  graduate-agent:
    command: ["alice --port 8030"]
    build:
      context: https://github.com/mostafatalaat770/aries-cloudagent-python.git#openapi-demo
      dockerfile: ./docker/Dockerfile.demo
    ports:
      - 8030-8037:8030-8037
    networks:
      - aca
    environment:
      - RUNMODE=${RUNMODE}
      - DOCKERHOST=${DOCKERHOST}
      - LEDGER_URL=${LEDGER_URL}
      - GENESIS_URL=${GENESIS_URL}
    tty: true
  company-agent:
    command: ["acme --port 8040"]
    build:
      context: https://github.com/mostafatalaat770/aries-cloudagent-python.git#openapi-demo
      dockerfile: ./docker/Dockerfile.demo
    ports:
      - 8040-8047:8040-8047
    networks:
      - aca
    environment:
      - RUNMODE=${RUNMODE}
      - DOCKERHOST=${DOCKERHOST}
      - LEDGER_URL=${LEDGER_URL}
      - GENESIS_URL=${GENESIS_URL}
    tty: true

  aca:
